### ISSUE TITLE
Background?

### ISSUE THREAD

**Issue by janpio** [BuddyLReno/cordova-plugin-media-duration-demo#4]
With your demo app, I now totally get why this is nicer.

But: What is the connection to the background service killing of ANdroid?

**Comment by BuddyLReno** [comment]
Sorry, been on thanksgiving holiday away from my email mostly. 

So android has a feature called [Doze](https://developer.android.com/training/monitoring-device-state/doze-standby), which greatly restricts background activity  in an effort to save battery. When Doze is active, things like `setTimeout` and `setInterval` no longer function because they're essentially brand new events that are attached and implemented at the browser level.

The browser that cordova is communicating with is no longer processing because of Doze mode. An event from cordova, because it's native ios/android code, allows the browser to wake up to process the code that fires from the native event. During that time, if you set a function to be called with a browser api event like `setTimeout` or `setInterval` starts to count down to execute. The main code from the native event finishes and the app goes back into the idle state, pausing browser processing. The `setTimeout` and/or `setInterval` also then pauses and never fires because it's a browser API separate from the main javascript thread.

**Comment by BuddyLReno** [comment]
If needed, I can draw up a diagram.

**Comment by janpio** [comment]
No need to apologize - you are teaching me stuff here.

Can Doze be triggered at the same time the app is open and displaying the duration (for the first time)?

**Comment by BuddyLReno** [comment]
:) No, Doze is only something that happens when the app goes into the background for a period of time. So if you switch to another app or go back to the home screen, your app is now in the background but not necessarily in Doze mode. From the android docs on Doze, here's when it activates:

> If a user leaves a device unplugged and stationary for a period of time, with the screen off, the device enters Doze mode. In Doze mode, the system attempts to conserve battery by restricting apps' access to network and CPU-intensive services. It also prevents apps from accessing the network and defers their jobs, syncs, and standard alarms.

So mainly, while the app is open, this isn't going to be a problem. But if you are creating a playlist like functionality like podcasts or music which would advance to the next track while the device is idle, that's when the problem would occur.

**Comment by janpio** [comment]
Ok, what is the usecase of duration for a playlist playing in the background?

**Comment by BuddyLReno** [comment]
So, there isn't a bulletproof use case for this.  Our particular app was calculating progress through the file and since we aren't able to get the duration of a file until it plays, we needed to be able to get that and save it to the audio file's model for future reference. By having the native code fire the event, it was much more consistent instead of having to continually ping for it.  Our API now includes the duration so we technically don't need duration in the background anymore, however, I believe that using a single callback that is fired once from native code when ready, is more elegant and a better structure to adhere to, especially considering that simply loading a file without playing it means duration will return a -1.

**Comment by janpio** [comment]
Ok, I was just wondering if I was just too dumb to see the direct connection between the new, useful method and the Doze problem - and this confused me a bit ;)

**Comment by BuddyLReno** [comment]
Nah, it's all good man! There's ways around "needing" it but if you don't have a reliable source for duration _before_ the track is played, having the track report to you what the duration is helps out. And you write less code!

**Comment by janpio** [comment]
Got it. Thanks.
